# Generated by Django 5.2.5 on 2025-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('hobbies', models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Tracel', 'Tracel'), ('Movies', 'Movies')], max_length=20)),
                ('source_of_income', models.CharField(choices=[('Employed', 'Employed'), ('Student', 'Student'), ('Business', 'Business'), ('Others', 'Others')], max_length=20)),
                ('income', models.PositiveIntegerField(default=20)),
                ('profile_pic', models.ImageField(blank=True, upload_to='Profile_pic/')),
                ('age', models.PositiveIntegerField(default=18)),
                ('bio', models.TextField(verbose_name='')),
            ],
        ),
    ]
